### ISSUE TITLE
error: Page Not Found 

### ISSUE THREAD

**Issue by malivinayak** [Shraddha-V22/mcr-6#1]
Once I add my rating it is throwing an error

![image](https://github.com/Shraddha-V22/mcr-6/assets/66154908/c994f1f8-79e1-4fbd-a929-3355d8fcae2a)

Which DB are you using ?

**Comment by malivinayak** [comment]
I Got the issue:

This Error page occurs only when I refresh the specific route
If you want to see this issue then try to access any food directly via url or refresh the page
[click here](https://food-for-taste.netlify.app/restaurant/1) - check the url now

`Solution`: You need to force redirect all routes via home route

If you need help regarding this you can ask me

**Comment by Shraddha-V22** [comment]
Everything is working fine in local. I will fix it.

**Comment by Shraddha-V22** [comment]
I have fixed the issue.

**Comment by malivinayak** [comment]
> I have fixed the issue. On Sat, 8 Jul, 2023, 10:34 pm Shraddha Vishwakarma, ***@***.***> wrote:

Yup
